// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250520142917_ToDoSeed")]
    partial class ToDoSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DateModified")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ToDoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToDoId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae6139d2-375c-40df-b5ab-293346277d2f"),
                            CreatedBy = "user1",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            Tekst = "We will overload the flux capacitors!",
                            ToDoId = new Guid("6cb4f5bb-764d-4344-9e29-35fc7b5e1d47")
                        });
                });

            modelBuilder.Entity("Domain.N2NEntities.UserToDo", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToDoId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedDate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ToDoId");

                    b.HasIndex("ToDoId");

                    b.ToTable("UserToDos");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("a3b1e294-c106-4dd4-bce1-a97132d16c3d"),
                            ToDoId = new Guid("6cb4f5bb-764d-4344-9e29-35fc7b5e1d47"),
                            AssignedDate = "5/20/2025 2:29:16 PM",
                            Id = new Guid("b68ec62d-c943-40ba-a652-3a226bb36a66")
                        },
                        new
                        {
                            UserId = new Guid("6d8de1aa-3d88-450a-a35c-408efd8f5bb2"),
                            ToDoId = new Guid("6cb4f5bb-764d-4344-9e29-35fc7b5e1d47"),
                            AssignedDate = "5/20/2025 2:29:16 PM",
                            Id = new Guid("32e4c3bb-900b-4dd5-b7f6-18277027985d")
                        });
                });

            modelBuilder.Entity("Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11b1a7f-c5e0-45a0-ba0f-f68435c826eb"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("121b4b8b-d3f9-4b88-ab11-857dc9941c3b"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Domain.ToDos.ToDo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DateEnd")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DateModified")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DateStart")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cb4f5bb-764d-4344-9e29-35fc7b5e1d47"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "HIGH",
                            RowVersion = 0u,
                            Status = "IN_PROGRESS",
                            Title = "Increase power to the warp engine"
                        },
                        new
                        {
                            Id = new Guid("47fb53da-e324-459e-9bb5-d2dccff741d7"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task1"
                        },
                        new
                        {
                            Id = new Guid("05fc5276-8a16-450d-ba3e-4760267ec381"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task2"
                        },
                        new
                        {
                            Id = new Guid("de734256-7f1a-403d-a14c-6bd545426e08"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task3"
                        },
                        new
                        {
                            Id = new Guid("ef66ce84-4ce5-468c-92da-4745160b4a8c"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task4"
                        },
                        new
                        {
                            Id = new Guid("1be3e19f-13fe-4c3b-953e-eedbdee16134"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task5"
                        },
                        new
                        {
                            Id = new Guid("0e70a5ca-5c3b-4ba4-a5c1-6a389a37f8df"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task6"
                        },
                        new
                        {
                            Id = new Guid("09345fd8-9400-48c7-85e8-e2d5e082ac11"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task7"
                        },
                        new
                        {
                            Id = new Guid("f5fee937-1a62-4c00-b1ee-fbcbeff1c8d9"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task8"
                        },
                        new
                        {
                            Id = new Guid("b4c862a8-4259-460d-a39e-d000df86f064"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task9"
                        },
                        new
                        {
                            Id = new Guid("b8647a3b-0711-4210-8397-d77376005a81"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task10"
                        },
                        new
                        {
                            Id = new Guid("562ed64a-2eac-4a12-83e9-5a7b9a32994f"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task11"
                        },
                        new
                        {
                            Id = new Guid("8daa8a57-fa0d-411e-9c8a-7ce7e657d4a9"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task12"
                        },
                        new
                        {
                            Id = new Guid("b7a41bb7-a2af-40fd-9f24-f1f31075760a"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task13"
                        },
                        new
                        {
                            Id = new Guid("9d7cfd09-f7bc-4333-9936-7afa35f441d1"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task14"
                        },
                        new
                        {
                            Id = new Guid("463ee6e5-a64a-4af5-b3c9-cc6915935784"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task15"
                        },
                        new
                        {
                            Id = new Guid("ea545c41-9030-4cff-ac92-ba7753beb98d"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task16"
                        },
                        new
                        {
                            Id = new Guid("e28821d5-c960-459a-9055-98e520d9b24b"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task17"
                        },
                        new
                        {
                            Id = new Guid("33f8daeb-192b-4253-8e6d-d075aaf110a6"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task18"
                        },
                        new
                        {
                            Id = new Guid("80bda57f-b222-405b-a1d5-59e3e8f3317c"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task19"
                        },
                        new
                        {
                            Id = new Guid("f450674b-12b3-458d-bb17-b30467a2d083"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task20"
                        },
                        new
                        {
                            Id = new Guid("78c897ad-b438-4b30-8781-faf82f66e819"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task21"
                        },
                        new
                        {
                            Id = new Guid("ce4b4e99-017f-4ce8-8b1f-39d9289690e4"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task22"
                        },
                        new
                        {
                            Id = new Guid("3fd41d79-582c-493a-a769-77cf6b0469b0"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task23"
                        },
                        new
                        {
                            Id = new Guid("e9e1bd12-2165-45ac-8824-0dd47ac0755f"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task24"
                        },
                        new
                        {
                            Id = new Guid("efa3a555-8c33-4106-8292-602d933bbb95"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task25"
                        },
                        new
                        {
                            Id = new Guid("38f30e6c-d554-43f1-b65b-49ed08fba319"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task26"
                        },
                        new
                        {
                            Id = new Guid("13c5d63b-a320-46b0-b3e5-7d205cfb7814"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task27"
                        },
                        new
                        {
                            Id = new Guid("909cb444-d959-45a4-b9b7-8503b061887f"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task28"
                        },
                        new
                        {
                            Id = new Guid("1797096f-fc95-4d78-9002-0976acdb6b31"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task29"
                        },
                        new
                        {
                            Id = new Guid("61497cf4-db7d-45f1-8a3d-7d9f5546b4a5"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task30"
                        },
                        new
                        {
                            Id = new Guid("b820cbd7-3c30-4ecc-b72a-e00351799414"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task31"
                        },
                        new
                        {
                            Id = new Guid("d1776d57-d568-4058-9f14-f3522ff9db09"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task32"
                        },
                        new
                        {
                            Id = new Guid("22c7b843-819d-4d3a-879d-891c86d271ef"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task33"
                        },
                        new
                        {
                            Id = new Guid("b72f8cb0-6dfc-4681-90d4-4c4a9b344935"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task34"
                        },
                        new
                        {
                            Id = new Guid("64452277-77ea-4087-bb50-b00bad7b8a12"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task35"
                        },
                        new
                        {
                            Id = new Guid("87df559c-cc00-4aec-af3e-51a8a3f49cbc"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task36"
                        },
                        new
                        {
                            Id = new Guid("d3fae83c-042c-438e-8cda-fc988de90130"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task37"
                        },
                        new
                        {
                            Id = new Guid("7e93a6c4-cbf7-4873-af17-3d133194c17d"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task38"
                        },
                        new
                        {
                            Id = new Guid("a544266b-a461-4d33-b426-01b540181617"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task39"
                        },
                        new
                        {
                            Id = new Guid("1dbd2445-9be3-496b-9f1d-02a093adcd78"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task40"
                        },
                        new
                        {
                            Id = new Guid("1ac1c57f-0754-4439-8366-f67c3c8d2770"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task41"
                        },
                        new
                        {
                            Id = new Guid("28d4e06a-a868-4524-b8d7-186ce0f40506"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task42"
                        },
                        new
                        {
                            Id = new Guid("dd166506-798b-4304-b988-f7c90494c3c4"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task43"
                        },
                        new
                        {
                            Id = new Guid("bd5bec0a-d954-4d04-99aa-17bbd003a712"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task44"
                        },
                        new
                        {
                            Id = new Guid("8a75e858-f606-4bca-8e07-a02ae2fafe20"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task45"
                        },
                        new
                        {
                            Id = new Guid("f453ff36-067b-45f9-9c46-4c312495166a"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task46"
                        },
                        new
                        {
                            Id = new Guid("9da798a1-3e6f-4183-81af-be347451ab77"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task47"
                        },
                        new
                        {
                            Id = new Guid("792910e4-f88b-4971-9766-246a5bac736c"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task48"
                        },
                        new
                        {
                            Id = new Guid("a553ddf9-eccd-4723-9d33-6e3e1045909b"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task49"
                        },
                        new
                        {
                            Id = new Guid("584a8ae5-d4cb-4f82-9252-b3fca8e53ce7"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "MED",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task50"
                        },
                        new
                        {
                            Id = new Guid("3c83b113-7134-4e9a-9b22-1a953367a426"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task51"
                        },
                        new
                        {
                            Id = new Guid("679829ad-fc67-42d0-9d9f-533b7eeacc6f"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task52"
                        },
                        new
                        {
                            Id = new Guid("919b1e72-b78e-4cb9-8978-a65a39ed21b6"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task53"
                        },
                        new
                        {
                            Id = new Guid("551a6e50-f9a7-4c79-86ec-e84edb7ec4ad"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task54"
                        },
                        new
                        {
                            Id = new Guid("6bdcb1f6-bfce-462b-afe2-8332a524399a"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task55"
                        },
                        new
                        {
                            Id = new Guid("4a6310f0-c348-40f5-a78a-a213855c75fc"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            DateEnd = "6/20/2025 2:29:16 PM",
                            DateModified = "5/20/2025 2:29:16 PM",
                            DateStart = "5/20/2025",
                            Priority = "LOW",
                            RowVersion = 0u,
                            Status = "TO_DO",
                            Title = "Task56"
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DateCreated")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DateModified")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d20b73cf-aab9-459a-90d5-2d9f65bd4f91"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            Email = "admin@example.com",
                            Password = "$2a$12$pCF8WvWAwvDtSKZJtpm9ZuPxiibhVEm4t9j8M1mAEjsa55UdVCyF2",
                            RoleId = new Guid("a11b1a7f-c5e0-45a0-ba0f-f68435c826eb"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("a3b1e294-c106-4dd4-bce1-a97132d16c3d"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            Email = "user@example.com",
                            Password = "$2a$12$KEY3WPXYB5ldI/fInlj3geJj12OCmXHu9AouvyKffORMypumTVtP.",
                            RoleId = new Guid("121b4b8b-d3f9-4b88-ab11-857dc9941c3b"),
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("6d8de1aa-3d88-450a-a35c-408efd8f5bb2"),
                            CreatedBy = "seed",
                            DateCreated = "5/20/2025 2:29:16 PM",
                            Email = "user2@example.com",
                            Password = "$2a$12$dHimz4GciBJHZTDs4BoqruADW.wgIEPckq2ceCbJTkX9F.8GC/QoO",
                            RoleId = new Guid("121b4b8b-d3f9-4b88-ab11-857dc9941c3b"),
                            Username = "user2"
                        });
                });

            modelBuilder.Entity("Domain.Comments.Comment", b =>
                {
                    b.HasOne("Domain.ToDos.ToDo", "ToDo")
                        .WithMany("Comments")
                        .HasForeignKey("ToDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDo");
                });

            modelBuilder.Entity("Domain.N2NEntities.UserToDo", b =>
                {
                    b.HasOne("Domain.ToDos.ToDo", "ToDo")
                        .WithMany("UserToDos")
                        .HasForeignKey("ToDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("UserToDos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToDo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.HasOne("Domain.Roles.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Roles.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.ToDos.ToDo", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("UserToDos");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("UserToDos");
                });
#pragma warning restore 612, 618
        }
    }
}
